
```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
```



```{r cars}
df <- read.table("kmer_completness.tsv", header = TRUE, sep = "\t")
```



```{r pressure, echo=FALSE}

df2 <- df %>%
  mutate(
    Haplotype = ifelse(grepl("hapA", Assembly), "hapA", "hapB"),
    Parent = case_when(
      grepl("^mom", Kmer_set_used) ~ "mom",
      grepl("^dad", Kmer_set_used) ~ "dad"
    ),
    Dataset = factor(Dataset,
                     levels = c("HG002","HG005","HG01109","HG01243")),
    Haplotype = factor(Haplotype, levels = c("hapA","hapB")),
    Method = factor(Method, levels = c("Hifiasm", "RFHap"))
  )

head(df2)
```

```{r}
completness_plot = ggplot(
  df2,
  aes(
    x = Haplotype,
    y = Completeness,
    group = interaction(Method, Dataset, Haplotype),
    shape = Parent,
    color = Method
  )
) +
  geom_line(linewidth = 0.6) +   
  geom_point(size = 3, ,
    position = position_dodge(width = 0.1)) +                           
  facet_grid(. ~ Dataset) +
  scale_y_continuous(limits = c(90, 100)) +
  labs(
    y = "Completeness (%)",
    x = NULL,
    shape = "Hapmer set",
    color = "Method"
  ) +
  theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    axis.text.x = element_text(size = 10),
    strip.text = element_text(face = "bold"), legend.position = "none"
  )
completness_plot
```

```{r}
kmer_qv <- read.table("kmer_qv.tsv", header = TRUE, sep = "\t")
kmer_qv = kmer_qv %>% mutate(Assembly = sub("\\..*", "", Assembly))

kmer_qv
```


```{r}
qv_plot = ggplot(
  kmer_qv,
  aes(
    x = Assembly,
    y = QV,
    color = Method,
    shape = Assembly,
    group = interaction(Method, Dataset, Assembly)
  )
) +
  geom_point(
    size = 3,
    position = position_dodge(width = 0.1)
  ) +
  facet_grid(. ~ Dataset) +
  scale_shape_manual(
    values = c(
      "hapA" = 17,  # triángulo
      "hapB" = 16   # círculo
    )
  ) +
  labs(
    y = "QV",
    x = NULL,
    color = "Method",
    shape = "Haplotype"
  ) +
  theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    axis.text.x = element_text(size = 10),
    strip.text = element_text(face = "bold"), legend.position = "bottom"
  ) + guides(shape = "none")

qv_plot
```

```{r}
library(patchwork)

png("kmer_metrics.png", res = 150, width = 1000, height = 1000)
(completness_plot / qv_plot) + plot_annotation(tag_levels = "A")
dev.off()
```

