---
title: "final_papers_figures"
output: html_document
date: "2025-01-22"
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(randomForest)
library(rmarkdown)
library(e1071)
library(caTools)
library(ggplot2)
library(dplyr)
library(forcats)
```

```{r}
rf_m64011=readRDS("train/m64011_190726_220327.Q20.fastq_fastkm_matrix_rf_model.rds")
rf_human_simplex=readRDS("train/human_simplex.fq_fastkm_matrix_rf_model.rds")
```

Feature Importance
```{r}
human_simplex_varImplot=varImpPlot(rf_human_simplex,main="Importance of features")
human_simplex_varImplot=as.data.frame(human_simplex_varImplot)
human_simplex_varImplot$feature=row.names(human_simplex_varImplot)

plot_h=human_simplex_varImplot %>% mutate(feature = fct_reorder(feature, MeanDecreaseGini)) %>% ggplot(aes(x = MeanDecreaseGini, y = feature)) +
  geom_point(size = 3, alpha = 0.6) +  # Adjust size and transparency
  geom_jitter(width = 0.2, height = 0) +  # Add jitter for better visibility
  theme_minimal() +  # Use a minimal theme
  labs(title = "Simplex", x = "MeanDecreaseGini", y = "Feature") +
  theme(text=element_text(size=35),axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5,size = 60))  # Rotate x-axis labels for better readability

m64011_varImplot=varImpPlot(rf_m64011,main="Importance of features")
m64011_varImplot=as.data.frame(m64011_varImplot)
m64011_varImplot$feature=row.names(m64011_varImplot)

plot_m6=m64011_varImplot %>% mutate(feature = fct_reorder(feature, MeanDecreaseGini)) %>% ggplot(aes(x = MeanDecreaseGini, y = feature)) +
  geom_point(size = 3, alpha = 0.6) +  # Adjust size and transparency
  geom_jitter(width = 0.2, height = 0) +  # Add jitter for better visibility
  theme_minimal() +  # Use a minimal theme
  labs(title = "HiFi", x = "MeanDecreaseGini", y = "Feature") +
  theme(text=element_text(size=35),axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5, size =60))  # Rotate x-axis labels for better readability

library(patchwork)
a=(plot_h | plot_m6) 
a 
```
Probility Distribution
```{r}
human_simplex_prob = read.delim("predict/human_simplex/rf_test/human_simplex.fq_fastkm_matrix.15_rf_prediction.txt", sep =" ")
prob_plot_h=ggplot(human_simplex_prob, aes(x = Predicted.prob.A, y = Predicted.prob.B, color = Predicted.Class)) +
  geom_point(size = 3) +
  labs(
    title = "",
    x = "A",
    y = "B",
    color = "Clase Predicha"
  ) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1), expand = c(0, 0)) +
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1), expand = c(0, 0)) + 
  theme_minimal()  + theme(legend.position = "none", text=element_text(size=50))

human_hifi_prob = read.delim("predict/hifi_human.fastq/rf_test/m84005_220919_232112_s2.hifi_reads.fastq_fastkm_matrix.15_rf_prediction.txt", sep =" ")
prob_plot_m=ggplot(human_hifi_prob, aes(x = Predicted.prob.A, y = Predicted.prob.B, color = Predicted.Class)) +
  geom_point(size = 3) +
  labs(
    title = "",
    x = "A",
    y = "B",
    color = "Predicted Class"
  ) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1), expand = c(0, 0)) +
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1), expand = c(0, 0)) +
  theme_minimal() + theme(legend.position = "right", text=element_text(size = 50))

library(patchwork)
b=(prob_plot_h | prob_plot_m) 

b
```

```{r}
simplex_density=human_hifi_prob[,c(4,5)]
hifi_human_density=human_simplex_prob[,c(4,5)]
```

```{r}
d1=ggplot(simplex_density, aes(x=Predicted.prob.A, y=Predicted.prob.B) ) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "Simplex") +
  theme(
    legend.position='none'
  ) 

d2= ggplot(hifi_human_density, aes(x=Predicted.prob.A, y=Predicted.prob.B) ) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(title = "HiFi")+
  theme(
    legend.position='right'
  ) 
```

```{r}
library(patchwork)
(d1 | d2) +
  plot_annotation(title = "Density Probability distribution", tag_levels = list(c("A", "B", "C"))) & 
  theme(plot.title = element_text(hjust = 0.5), plot.tag = element_text(size = 15, face = "bold"))
```

```{r}
library(tidyverse)
library(caret)
library(randomForest)
library(e1071)
library(caTools)
library(ggplot2)
library(dplyr)

sd=read.delim("predict/human_simplex/rf_test/pred_metrics.txt", header=TRUE, sep=" ")
head(sd)

library(patchwork)
p1=sd %>% filter(class != "U") %>% ggplot(aes(y=Precision, x=factor(k),fill=class)) +
  geom_col(position="dodge2") +
  xlab("")+
  theme_minimal() +
  coord_cartesian(ylim = c(0.1, 1)) + ggtitle("") + theme(text=element_text(size = 40),legend.position = "none") 
p2=sd %>% filter(class != "U") %>% ggplot(aes(y=Recall, x=factor(k),fill=class)) +
  geom_col(position="dodge2")  +
  xlab("k-mer classifier")+
  theme_minimal()+
  coord_cartesian(ylim = c(0.1, 1)) + theme(text=element_text(size = 40),legend.position = "none")
p3=sd %>% filter(class != "U") %>% ggplot(aes(y=F1, x=factor(k),fill=class)) +
  geom_col(position="dodge2")  +
  xlab("")+
  theme_minimal()+
  coord_cartesian(ylim = c(0.1, 1)) + theme(text=element_text(size = 40),legend.position = "none")

simplex_metrics=p1+p2+p3 

simplex_metrics

```
```{r}
library(tidyverse)
library(caret)
library(randomForest)
library(e1071)
library(caTools)
library(ggplot2)
library(dplyr)

sd=read.delim("predict/hifi_human.fastq/rf_test/pred_metrics.txt", header=TRUE, sep=" ")
head(sd)

library(patchwork)
p1=sd %>% filter(class != "U") %>% ggplot(aes(y=Precision, x=factor(k),fill=class)) +
  geom_col(position="dodge2") +
  xlab("")+
  theme_minimal() + 
  coord_cartesian(ylim = c(0.1, 1)) + ggtitle("") +theme(text=element_text(size = 50) , legend.position = "none", plot.title = element_text(hjust=0))

p2=sd %>% filter(class != "U") %>% ggplot(aes(y=Recall, x=factor(k),fill=class)) +
  geom_col(position="dodge2")  +
  xlab("k-mer classifier")+
  theme_minimal()+ 
  coord_cartesian(ylim = c(0.1, 1)) + theme(text=element_text(size = 50), legend.position = "none")

p3=sd %>% filter(class != "U") %>% ggplot(aes(y=F1, x=factor(k),fill=class)) +
  geom_col(position="dodge2")  +
  xlab("")+
  theme_minimal()+
  coord_cartesian(ylim = c(0.1, 1)) + theme(text=element_text(size = 50), legend.position = "right")

hifi_metrics=p1+p2+p3

hifi_metrics = hifi_metrics 

hifi_metrics
```
```{r}
library(patchwork)
metrics = (simplex_metrics | hifi_metrics) +
  plot_annotation(title = "") & 
  theme(plot.title = element_text(hjust = 0.5))
metrics

```
```{r}
library(patchwork)

png("super_figure.png", width = 3500 , height = 3500)
(a/metrics/b) 
dev.off()
```

