---
title: "more_coverage_statistic_v2.Rmd"
output: html_document
date: "2025-08-26"
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(janitor)
library(stringr)
library(patchwork)
library(scales)
library(tidyr)
```

```{r cars}
hg00_wg=read.delim("new_stats_v3.tsv", sep ="\t", header=TRUE)

```

```{r}
hg00_wg = hg00_wg %>% mutate(
  N50merqury = as.numeric(gsub("\\,","",N50merqury)),
  Assembly=trimws(Assembly),
  N50gfastats=as.numeric(N50gfastats),
  AvgBlockSize = as.numeric(gsub(",","",AvgBlockSize))
) %>%
  mutate(
    SwitchErrorMerqury=as.numeric(gsub("%","",SwitchErrorMerqury))
  ) %>% filter(Method != "TrioBinning")
```

####Errors

```{r}
e=ggplot(hg00_wg, aes(x = Assembly, y = SwitchErrorMerqury, fill = Method)) +
  geom_bar(stat = "identity", position = "dodge") +
  #geom_text(aes(label = round(SwitchErrorMerqury, 2)),
   #         position = position_dodge(width = 0.9),
    #        vjust = -0.3,        # etiqueta encima de la barra
     #       color = "black",
      #      size = 2.5) +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap(~Dataset, scales = "free_y") +
  labs(
    title = "Merqury Switch Error",
    x = "Assembly",
    y = "Merqury Switch Error",
    fill = "Method"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), title = element_text(size = 10), legend.position = "none"
  ) 

e
```

```{r}
df_long <- hg00_wg %>% 
  pivot_longer(
    cols = c(N50gfastats, N50merqury),
    names_to = "Metric",
    values_to = "N50"
  )
```




```{r}
pd <- position_dodge(width = 0.5)

n50 = ggplot(
  df_long,
  aes(
    x = Assembly,
    y = N50,
    color = Method,
    shape = Metric,
    group = interaction(Assembly, Method)
  )
) +
  geom_line(
    position = pd,
    linewidth = 0.8,
    alpha = 0.9
  ) +
  geom_point(
    size = 3.5,
    alpha = 0.9,
    position = pd
  ) +
  facet_wrap(~ Dataset, scales = "free_y") +
  scale_y_continuous(
    labels = scales::label_number(
      scale = 1e-6,
      suffix = "M",
      accuracy = 1
    )
  ) +
  scale_shape_manual(
    values = c(
      N50gfastats = 16,
      N50merqury  = 17
    )
  ) +
  scale_color_brewer(palette = "Set2") +
  theme_bw() +
  labs(
    x = "Assembly",
    y = "NG50 (Mb)",
    color = "Method",
    shape = "Metric",
    title = "NG50 comparison by assembly, method, and dataset"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), title = element_text(size = 10), legend.position = "bottom"
  ) 

```



```{r}
library(patchwork)

png("Figure2.png", width =2000, height =1500 , res=200)
(n50 | e) + 
  plot_annotation(tag_levels = "A")
dev.off()
```

