---
title: "merqury_Tables"
author: "damigonzalez"
date: "2024-12-18"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```


```{r cars}
merqury_stats <- read.delim("merqury_new_stats.tsv", sep="\t", header=TRUE)
head(merqury_stats)
```
```{r}
merqury_stats <- merqury_stats %>%
  mutate(across(-1, ~ as.numeric(gsub("[^0-9.]", "", .))))
glimpse(merqury_stats)
head(merqury_stats)

merqury_stats$Assembly.. <- factor(merqury_stats$Assembly.., levels = merqury_stats$Assembly..)
merqury_stats
```


```{r pressure, echo=FALSE}
merqury_stats <- merqury_stats %>%
  mutate(Sequence_type=case_when(
    grepl("ONT",Assembly..) ~ "ONT",
    grepl("PB",Assembly..) ~ "PB"))%>% 
    mutate(Sex=case_when(
    grepl("maternal",Assembly..) ~ "maternal",
    grepl("paternal",Assembly..) ~ "paternal"))%>%
  mutate(Sequence_type = factor(Sequence_type, levels = c("ONT", "PB")))%>%
  mutate(Sex = factor(Sex, levels = c("maternal", "paternal")))

merqury_stats
```



```{r}
a=ggplot(merqury_stats, aes(x = Assembly.., y = Total_kmers, fill = Sequence_type, alpha = Sex)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none", text = element_text(size = 16)) +
  scale_alpha_manual(values = c(0.5, 1 , 0.5, 1 , 0.5 , 1 , 0.5 ,1)) +
  scale_y_continuous(labels = scales::comma)+# Ajusta los valores de alpha para cada tipo
  labs(title = "Total kmers per Asembly", x = "Assembly", y = "Total kmers")
```


```{r}
b=ggplot(merqury_stats, aes(x = Assembly.., y = N50, fill = Sequence_type, alpha = Sex)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none", text = element_text(size = 16)) +
  scale_alpha_manual(values = c(0.5, 1 , 0.5, 1 , 0.5 , 1 , 0.5 ,1)) +
  scale_y_continuous(labels = scales::comma)+# Ajusta los valores de alpha para cada tipo
  labs(title = "N50 per Asembly", x = "Assembly", y = "N50")
```

```{r}
c=ggplot(merqury_stats, aes(x = Assembly.., y = Total_opposite_kmers, fill = Sequence_type, alpha = Sex)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none",text = element_text(size = 16)) +
  scale_alpha_manual(values = c(0.5, 1 , 0.5, 1 , 0.5 , 1 , 0.5 ,1)) +
  scale_y_continuous(labels = scales::comma)+# Ajusta los valores de alpha para cada tipo
  labs(title = "Total opposite kmers per Asembly", x = "Assembly", y = "Total opposite kmkers")
```

```{r}
d=ggplot(merqury_stats, aes(x = Assembly.., y = Switch_error, fill = Sequence_type, alpha = Sex)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none", text = element_text(size = 16)) +
  scale_alpha_manual(values = c(0.5, 1 , 0.5, 1 , 0.5 , 1 , 0.5 ,1)) +
  labs(title = "Switch error per Asembly", x = "Assembly", y = "Switch Error Rate")
```


```{r}
library(patchwork)

png("merqury_metrics.png", width = 1300 , height = 1000)
 (a | b)/(c | d) + 
  plot_annotation(tag_levels = 'A')

```

