---

---

```{r setup, include=FALSE}
library(readxl)

df <- read_excel("read_metrics.xlsx")
df
```



```{r cars}


library(gt)

tbl <- df |>
  gt() |>
  fmt_missing(
    everything(),
    missing_text = ""
  ) |>
  tab_style(
    style = cell_text(color = "black"),
    locations = cells_body()
  ) |>
  tab_style(
    style = cell_text(color = "black"),
    locations = cells_column_labels()
  ) |>
  tab_style(
    style = cell_text(color = "black"),
    locations = cells_title()
  ) |>
  tab_options(
    table.font.names = "Times New Roman",
    table.font.size = px(10),
    heading.align = "center",
    column_labels.font.weight = "bold",
    data_row.padding = px(3),
    table.border.top.style = "solid",
    table.border.bottom.style = "solid",
    table.border.top.width = px(1),
    table.border.bottom.width = px(1),
    column_labels.border.bottom.style = "solid",
    column_labels.border.bottom.width = px(1),
    table_body.hlines.style = "none"
  ) |>
  opt_all_caps() |>
  opt_table_outline()


tbl
```


```{r pressure, echo=FALSE}
gtsave(
  tbl,
  filename = "Suplementary_table_1.png",
  zoom = 2    # MUY importante para calidad editorial
)
```

